using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using Danfma.MySheet.Expressions;
using Danfma.MySheet.Parsing;

namespace Danfma.MySheet.Tests;

/// <summary>
/// M6 golden-file guard for the <c>MSWM</c> container's Brotli body versions. Before <c>WorkbookCompression
/// .Brotli</c> switched its DEFAULT write encoding from v2 (whole-buffer Brotli) to v3 (fixed-64KB-chunked
/// Brotli — see the format comment atop Workbook.Serialization.cs), this test's fixture was generated by the
/// pre-M6 code and frozen in git: it is the ONLY thing that still exercises the v2 READ path once nothing in
/// this repository writes v2 anymore. <c>Fixtures/container-v2-brotli-warm.bin</c> is a warm-start
/// (<see cref="WorkbookSaveOptions.IncludeComputedValues"/> = true) container over the same small sample
/// workbook used by <see cref="WarmStartSaveLoadTests"/>/<see cref="WorkbookCompressionTests"/> (A1=1, A2=2,
/// A3=SUM(A1:A2), value cache populated before saving). DO NOT regenerate this file — v2 write support was
/// deliberately removed (a one-way boundary, same policy as the shared-formula tags 319-321): the fixture
/// must keep proving the OLD bytes still load, not the new writer's output.
/// </summary>
public class ContainerVersionCompatibilityTests
{
    private const string FixtureFileName = "container-v2-brotli-warm.bin";

    private static Workbook Sample()
    {
        var workbook = new Workbook();
        var sheet = workbook.Sheets.Add("Sheet1");
        sheet["A1"] = new NumberValue(1);
        sheet["A2"] = new NumberValue(2);
        sheet["A3"] = ExpressionParser.Parse("=SUM(A1:A2)", sheet);
        return workbook;
    }

    [Test]
    public async Task GoldenV2Fixture_IsVersion2_AndLoadsForever()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", FixtureFileName);
        var bytes = await File.ReadAllBytesAsync(path);

        await Assert.That(bytes.AsSpan(0, 4).ToArray()).IsEquivalentTo("MSWM"u8.ToArray());
        await Assert.That(bytes[4]).IsEqualTo((byte)2); // frozen: the v2 (whole-buffer Brotli) body encoding

        var loaded = Workbook.Load(path);
        await Assert.That(loaded.GetCellValue("Sheet1", "A3").ToDouble()).IsEqualTo(3.0);
    }

    // Fixture generator — intentionally NOT a [Test] (same convention as MemoryPackCompatibilityTests). The
    // fixture was produced ONCE, by the pre-M6 code (Brotli container default = v2), and is frozen in git;
    // v2 write support no longer exists, so this method can never be re-run against current code to
    // reproduce it — it is kept only as a record of how the frozen bytes were made.
    private static void GenerateFixture([CallerFilePath] string sourcePath = "")
    {
        var directory = Path.Combine(Path.GetDirectoryName(sourcePath)!, "Fixtures");
        Directory.CreateDirectory(directory);

        var workbook = Sample();
        workbook.GetCellValue("Sheet1", "A3"); // populate the cache before a warm save

        workbook.Save(
            Path.Combine(directory, FixtureFileName),
            new WorkbookSaveOptions
            {
                IncludeComputedValues = true,
                Compression = WorkbookCompression.Brotli,
            }
        );
    }
}
